In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_af2f6fddd4534648be3a64f49390c5cf = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='98u8RpH9cmpkfxGtDS-gE3j7pu_qrvCVt8m2xNyjde2M',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_af2f6fddd4534648be3a64f49390c5cf.get_object(Bucket='exam1-donotdelete-pr-iv3i36cdspczue',Key='diabetes.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()



Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [4]:
x= dataset.iloc[:,0:8]

In [5]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [6]:
y= dataset.iloc[:,8].values

In [7]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1,

In [8]:
from sklearn.model_selection import train_test_split                #previously cros_validation was used in sklearn
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)           #previously cros_validation was used in sklearn


In [9]:
x_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
661            1      199             76             43        0  42.9   
122            2      107             74             30      100  33.6   
113            4       76             62              0        0  34.0   
14             5      166             72             19      175  25.8   
529            0      111             65              0        0  24.6   
103            1       81             72             18       40  26.6   
338            9      152             78             34      171  34.2   
588            3      176             86             27      156  33.3   
395            2      127             58             24      275  27.7   
204            6      103             72             32      190  37.7   
31             3      158             76             36      245  31.6   
546            5      187             76             27      207  43.6   
278            5      114             74              0        0  24.9   
593            2       82             52             22      115  28.5   
737            8       65             72             23        0  32.0   
202            0      108             68             20        0  27.3   
175            8      179             72             42      130  32.7   
55             1       73             50             10        0  23.0   
479            4      132             86             31        0  28.0   
365            5       99             54             28       83  34.0   
417            4      144             82             32        0  38.5   
577            2      118             80              0        0  42.9   
172            2       87              0             23        0  28.9   
352            3       61             82             28        0  34.4   
27             1       97             66             15      140  23.2   
605            1      124             60             32        0  35.8   
239            0      104             76              0        0  18.4   
744           13      153             88             37      140  40.6   
79             2      112             66             22        0  25.0   
496            5      110             68              0        0  26.0   
..           ...      ...            ...            ...      ...   ...   
413            1      143             74             22       61  26.2   
694            2       90             60              0        0  23.5   
698            4      127             88             11      155  34.5   
386            5      116             74             29        0  32.3   
456            1      135             54              0        0  26.7   
728            2      175             88              0        0  22.9   
71             5      139             64             35      140  28.6   
49             7      105              0              0        0   0.0   
210            2       81             60             22        0  27.7   
409            1      172             68             49      579  42.4   
503            7       94             64             25       79  33.3   
37             9      102             76             37        0  32.9   
687            1      107             50             19        0  28.3   
48             7      103             66             32        0  39.1   
261            3      141              0              0        0  30.0   
653            2      120             54              0        0  26.8   
331            2       87             58             16       52  32.7   
568            4      154             72             29      126  31.3   
196            1      105             58              0        0  24.3   
76             7       62             78              0        0  32.6   
64             7      114             66              0        0  32.8   
671            1       99             58             10        0  25.4   
52       

In [10]:
import keras #Building neural network model back end it has tensorflow
from keras.models import Sequential # initializing model
from keras.layers import Dense # used for adding the neural network layers

Using TensorFlow backend.


In [11]:
model=Sequential()#instance

In [12]:
model.add(Dense(input_dim=8,init="random_uniform",activation="relu",output_dim=5)) #input_dim=no of neurons to have in the input layer(no of independent variables),init=adding weights,activation function,output_dim=next hidden layer
#best thing for output_dim is input_dim/2

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=8, units=5, kernel_initializer="random_uniform")`
  if __name__ == '__main__':


In [13]:
model.add(Dense(output_dim=5,init="random_uniform",activation="sigmoid"))# adding hidden layer similary like adding weights

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=5, kernel_initializer="random_uniform")`
  if __name__ == '__main__':


In [14]:
model.add(Dense(output_dim=1,init="random_uniform"))#adding output layer

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  if __name__ == '__main__':


In [15]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])#adam=batch gradent descent

In [16]:
model.fit(x_train,y_train,epochs=600,batch_size=10)#epochs no of iteration 

Epoch 1/600
614/614 [==============================] - 0s 611us/step - loss: 0.8993 - acc: 0.6401
Epoch 2/600
614/614 [==============================] - 0s 360us/step - loss: 0.6758 - acc: 0.6401
Epoch 3/600
614/614 [==============================] - 0s 474us/step - loss: 0.6509 - acc: 0.6401
Epoch 4/600
614/614 [==============================] - 0s 475us/step - loss: 0.6448 - acc: 0.6401
Epoch 5/600
614/614 [==============================] - 0s 476us/step - loss: 0.6414 - acc: 0.6401
Epoch 6/600
614/614 [==============================] - 0s 483us/step - loss: 0.6382 - acc: 0.6401
Epoch 7/600
614/614 [==============================] - 0s 480us/step - loss: 0.6358 - acc: 0.6401
Epoch 8/600
614/614 [==============================] - 0s 375us/step - loss: 0.6325 - acc: 0.6401
Epoch 9/600
614/614 [==============================] - 0s 470us/step - loss: 0.6285 - acc: 0.6401
Epoch 10/600
614/614 [==============================] - 0s 474us/step - loss: 0.6290 - acc: 0.6401
Epoch 11/600
614/61

In [17]:
y_predict=model.predict(x_test)

In [18]:
y_predict

array([[ 1.03242898],
       [ 0.19446427],
       [ 0.00146115],
       [ 0.66158134],
       [ 0.13429976],
       [-0.08369577],
       [ 0.72800428],
       [ 0.78208607],
       [ 0.39506453],
       [ 0.4536615 ],
       [ 0.57186836],
       [ 0.89932317],
       [ 0.37776059],
       [ 0.14183283],
       [ 0.11846781],
       [ 0.20035034],
       [ 0.85652477],
       [-0.16174257],
       [ 0.54841512],
       [ 0.27593488],
       [ 0.592053  ],
       [ 0.43613261],
       [ 0.33737677],
       [ 0.03228402],
       [-0.0143761 ],
       [ 0.45172256],
       [-0.03114349],
       [ 0.90833396],
       [ 0.13738889],
       [ 0.16080397],
       [ 0.54209679],
       [ 0.26284367],
       [ 0.09109092],
       [ 0.45280737],
       [ 0.12985593],
       [ 0.63964051],
       [ 0.52745098],
       [ 0.09518456],
       [ 0.37595934],
       [ 0.76878399],
       [ 0.28723103],
       [ 0.17855418],
       [ 0.19650966],
       [ 0.88293344],
       [ 0.8035112 ],
       [-0

In [19]:
y_predict1=(y_predict>0.5)

In [20]:
y_predict1

array([[ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [

In [21]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [22]:
x_test.shape

(154, 8)

In [35]:
y_predict2=model.predict((np.array([[6,148,72,35,0,33.6,0.627,50]])))
a=model.predict_classes((np.array([[2,99,60,17,160,36.6,0.453,21]])))
a

array([[0]], dtype=int32)

In [36]:
y_predict2

array([[ 0.68162674]], dtype=float32)

In [37]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict1)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict1)

0.7857142857142857

In [38]:
model.save('diabetes.h5')

In [39]:
get_ipython().system(u'tar -zcvf diabetes.tgz diabetes.h5')

diabetes.h5


In [40]:
import watson_machine_learning_client

In [41]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [42]:
wml_credentials={

"url":"https://eu-gb.ml.cloud.ibm.com",
"access_key":"nnZiIDyW8JYMd_nIW-gAOs5UvZNTrN7s5NjgSdttEnSv",
"username":"9ec85d17-4cef-42ea-84a1-335b275bb6d3",
"password":"c8695961-6225-414b-b755-80a1ca2fdfef",
"instance_id": "305de161-527c-49c8-a2e9-469a6e830390" 
}

In [43]:
client=WatsonMachineLearningAPIClient(wml_credentials)

In [44]:
metadata={
    client.repository.ModelMetaNames.NAME:"keras model",
    client.repository.ModelMetaNames.FRAMEWORK_NAME:"tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES:[{'name':'keras','version':'2.1.3'}],
    client.repository.ModelMetaNames.FRAMEWORK_VERSION:"1.5"
}

In [45]:
print(keras.__version__)

2.1.4


In [46]:
model_details=client.repository.store_model(model="diabetes.tgz",meta_props=metadata)

In [47]:
model_id = model_details["metadata"]["guid"]
model_deployment_details = client.deployments.create(artifact_uid=model_id,name="deployment")



#######################################################################################

Synchronous deployment creation for uid: '5f080b15-3c08-443f-8e89-9f6ec5bf5afb' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='5d6e6df5-986d-43ed-a295-d9c8143d5377'
------------------------------------------------------------------------------------------------




In [48]:
model_id = model_details["metadata"]["guid"]

In [49]:
model_id

'5f080b15-3c08-443f-8e89-9f6ec5bf5afb'

In [50]:
scoring_endpoint=client.deployments.get_scoring_url(model_deployment_details)

In [51]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/305de161-527c-49c8-a2e9-469a6e830390/deployments/5d6e6df5-986d-43ed-a295-d9c8143d5377/online'